# Generated by Django 5.2.4 on 2025-09-08 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="Enter features separated by line breaks",
                        null=True,
                    ),
                ),
                (
                    "use_cases",
                    models.TextField(
                        blank=True,
                        help_text="Enter use cases separated by line breaks",
                        null=True,
                    ),
                ),
                ("demo_link", models.URLField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
