# Generated by Django 5.2.4 on 2025-09-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="demo_link",
        ),
    ]
