# Generated by Django 5.2.4 on 2025-09-05 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="careers",
            fields=[
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("position", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FT", "تمام وقت"),
                            ("PT", "پاره وقت"),
                            ("PR", "پروژه\u200cای"),
                            ("IN", "کارآموزی"),
                        ],
                        default="FT",
                        max_length=2,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
